version: "3,7"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: suppliers
    ports:
      - 5432:5432
    volumes:
      - /postgres:/var/lib/postgresql/data